-- データベース接続テスト
describe("Database Connection", function()
    local helper = require("tests.test_helper")
    local db
    
    before_each(function()
        db = helper.setup_db()
    end)
    
    after_each(function()
        helper.teardown_db(db)
    end)
    
    it("should connect to database successfully", function()
        assert.is_not_nil(db)
    end)
    
    it("should execute simple query", function()
        local res, err = db:query("SELECT 1 as test")
        assert.is_nil(err)
        assert.is_not_nil(res)
        assert.equals(1, res[1].test)
    end)
    
    it("should retrieve PostgreSQL version", function()
        local res, err = db:query("SELECT version() as version")
        assert.is_nil(err)
        assert.is_not_nil(res)
        assert.is_not_nil(res[1].version)
    end)
    
    it("should verify users table exists", function()
        local res, err = db:query("SELECT * FROM information_schema.tables WHERE table_name = 'users'")
        assert.is_nil(err)
        assert.is_not_nil(res)
        assert.equals(1, #res)
    end)
    
    it("should verify posts table exists", function()
        local res, err = db:query("SELECT * FROM information_schema.tables WHERE table_name = 'posts'")
        assert.is_nil(err)
        assert.is_not_nil(res)
        assert.equals(1, #res)
    end)
    
    it("should verify categories table exists", function()
        local res, err = db:query("SELECT * FROM information_schema.tables WHERE table_name = 'categories'")
        assert.is_nil(err)
        assert.is_not_nil(res)
        assert.equals(1, #res)
    end)
    
    it("should verify tags table exists", function()
        local res, err = db:query("SELECT * FROM information_schema.tables WHERE table_name = 'tags'")
        assert.is_nil(err)
        assert.is_not_nil(res)
        assert.equals(1, #res)
    end)
    
    it("should have default admin user", function()
        local res, err = db:query("SELECT * FROM users WHERE username = 'admin'")
        assert.is_nil(err)
        assert.is_not_nil(res)
        assert.equals(1, #res)
        assert.equals("admin", res[1].username)
        assert.equals("admin", res[1].role)
    end)
    
    it("should have default categories", function()
        local res, err = db:query("SELECT COUNT(*) as count FROM categories")
        assert.is_nil(err)
        assert.is_not_nil(res)
        assert.is_true(res[1].count >= 3)
    end)
end)
